-- SYSTEM messages are generated by booking transitions rather than typed by a person.
CREATE TYPE "MessageKind" AS ENUM ('TEXT','SYSTEM');
ALTER TABLE "Message" ADD COLUMN "kind" "MessageKind" NOT NULL DEFAULT 'TEXT';
ALTER TABLE "Message" ADD COLUMN "metadata" JSONB;
