export enum EmailType {
  BOOKING_CONFIRMATION = 'BOOKING_CONFIRMATION',
  BOOKING_REMINDER = 'BOOKING_REMINDER',
  BOOKING_CANCELLATION_MODIFICATION = 'BOOKING_CANCELLATION_MODIFICATION',
  NEW_MESSAGE_OR_REVIEW = 'NEW_MESSAGE_OR_REVIEW',
  OTHER = 'OTHER',
}